version: '3.9'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: ai_platform
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
